// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network/network.proto

package com.blastedstudios.thrall.network;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetVehicleStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.NetVehicleState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float pos_x = 1;</code>
     */
    float getPosX();

    /**
     * <code>optional float pos_y = 2;</code>
     */
    float getPosY();

    /**
     * <code>optional float vel_x = 3;</code>
     */
    float getVelX();

    /**
     * <code>optional float vel_y = 5;</code>
     */
    float getVelY();
  }
  /**
   * Protobuf type {@code proto.NetVehicleState}
   */
  public  static final class NetVehicleState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.NetVehicleState)
      NetVehicleStateOrBuilder {
    // Use NetVehicleState.newBuilder() to construct.
    private NetVehicleState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetVehicleState() {
      posX_ = 0F;
      posY_ = 0F;
      velX_ = 0F;
      velY_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NetVehicleState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              posX_ = input.readFloat();
              break;
            }
            case 21: {

              posY_ = input.readFloat();
              break;
            }
            case 29: {

              velX_ = input.readFloat();
              break;
            }
            case 45: {

              velY_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blastedstudios.thrall.network.Messages.internal_static_proto_NetVehicleState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blastedstudios.thrall.network.Messages.internal_static_proto_NetVehicleState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blastedstudios.thrall.network.Messages.NetVehicleState.class, com.blastedstudios.thrall.network.Messages.NetVehicleState.Builder.class);
    }

    public static final int POS_X_FIELD_NUMBER = 1;
    private float posX_;
    /**
     * <code>optional float pos_x = 1;</code>
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POS_Y_FIELD_NUMBER = 2;
    private float posY_;
    /**
     * <code>optional float pos_y = 2;</code>
     */
    public float getPosY() {
      return posY_;
    }

    public static final int VEL_X_FIELD_NUMBER = 3;
    private float velX_;
    /**
     * <code>optional float vel_x = 3;</code>
     */
    public float getVelX() {
      return velX_;
    }

    public static final int VEL_Y_FIELD_NUMBER = 5;
    private float velY_;
    /**
     * <code>optional float vel_y = 5;</code>
     */
    public float getVelY() {
      return velY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (posX_ != 0F) {
        output.writeFloat(1, posX_);
      }
      if (posY_ != 0F) {
        output.writeFloat(2, posY_);
      }
      if (velX_ != 0F) {
        output.writeFloat(3, velX_);
      }
      if (velY_ != 0F) {
        output.writeFloat(5, velY_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (posX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, posX_);
      }
      if (posY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posY_);
      }
      if (velX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, velX_);
      }
      if (velY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, velY_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blastedstudios.thrall.network.Messages.NetVehicleState)) {
        return super.equals(obj);
      }
      com.blastedstudios.thrall.network.Messages.NetVehicleState other = (com.blastedstudios.thrall.network.Messages.NetVehicleState) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getPosX())
          == java.lang.Float.floatToIntBits(
              other.getPosX()));
      result = result && (
          java.lang.Float.floatToIntBits(getPosY())
          == java.lang.Float.floatToIntBits(
              other.getPosY()));
      result = result && (
          java.lang.Float.floatToIntBits(getVelX())
          == java.lang.Float.floatToIntBits(
              other.getVelX()));
      result = result && (
          java.lang.Float.floatToIntBits(getVelY())
          == java.lang.Float.floatToIntBits(
              other.getVelY()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + POS_X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosX());
      hash = (37 * hash) + POS_Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPosY());
      hash = (37 * hash) + VEL_X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVelX());
      hash = (37 * hash) + VEL_Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVelY());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blastedstudios.thrall.network.Messages.NetVehicleState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blastedstudios.thrall.network.Messages.NetVehicleState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.NetVehicleState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.NetVehicleState)
        com.blastedstudios.thrall.network.Messages.NetVehicleStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blastedstudios.thrall.network.Messages.internal_static_proto_NetVehicleState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blastedstudios.thrall.network.Messages.internal_static_proto_NetVehicleState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blastedstudios.thrall.network.Messages.NetVehicleState.class, com.blastedstudios.thrall.network.Messages.NetVehicleState.Builder.class);
      }

      // Construct using com.blastedstudios.thrall.network.Messages.NetVehicleState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        posX_ = 0F;

        posY_ = 0F;

        velX_ = 0F;

        velY_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blastedstudios.thrall.network.Messages.internal_static_proto_NetVehicleState_descriptor;
      }

      public com.blastedstudios.thrall.network.Messages.NetVehicleState getDefaultInstanceForType() {
        return com.blastedstudios.thrall.network.Messages.NetVehicleState.getDefaultInstance();
      }

      public com.blastedstudios.thrall.network.Messages.NetVehicleState build() {
        com.blastedstudios.thrall.network.Messages.NetVehicleState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blastedstudios.thrall.network.Messages.NetVehicleState buildPartial() {
        com.blastedstudios.thrall.network.Messages.NetVehicleState result = new com.blastedstudios.thrall.network.Messages.NetVehicleState(this);
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.velX_ = velX_;
        result.velY_ = velY_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blastedstudios.thrall.network.Messages.NetVehicleState) {
          return mergeFrom((com.blastedstudios.thrall.network.Messages.NetVehicleState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blastedstudios.thrall.network.Messages.NetVehicleState other) {
        if (other == com.blastedstudios.thrall.network.Messages.NetVehicleState.getDefaultInstance()) return this;
        if (other.getPosX() != 0F) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0F) {
          setPosY(other.getPosY());
        }
        if (other.getVelX() != 0F) {
          setVelX(other.getVelX());
        }
        if (other.getVelY() != 0F) {
          setVelY(other.getVelY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blastedstudios.thrall.network.Messages.NetVehicleState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blastedstudios.thrall.network.Messages.NetVehicleState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float posX_ ;
      /**
       * <code>optional float pos_x = 1;</code>
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>optional float pos_x = 1;</code>
       */
      public Builder setPosX(float value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float pos_x = 1;</code>
       */
      public Builder clearPosX() {
        
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>optional float pos_y = 2;</code>
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>optional float pos_y = 2;</code>
       */
      public Builder setPosY(float value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float pos_y = 2;</code>
       */
      public Builder clearPosY() {
        
        posY_ = 0F;
        onChanged();
        return this;
      }

      private float velX_ ;
      /**
       * <code>optional float vel_x = 3;</code>
       */
      public float getVelX() {
        return velX_;
      }
      /**
       * <code>optional float vel_x = 3;</code>
       */
      public Builder setVelX(float value) {
        
        velX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float vel_x = 3;</code>
       */
      public Builder clearVelX() {
        
        velX_ = 0F;
        onChanged();
        return this;
      }

      private float velY_ ;
      /**
       * <code>optional float vel_y = 5;</code>
       */
      public float getVelY() {
        return velY_;
      }
      /**
       * <code>optional float vel_y = 5;</code>
       */
      public Builder setVelY(float value) {
        
        velY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float vel_y = 5;</code>
       */
      public Builder clearVelY() {
        
        velY_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.NetVehicleState)
    }

    // @@protoc_insertion_point(class_scope:proto.NetVehicleState)
    private static final com.blastedstudios.thrall.network.Messages.NetVehicleState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blastedstudios.thrall.network.Messages.NetVehicleState();
    }

    public static com.blastedstudios.thrall.network.Messages.NetVehicleState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetVehicleState>
        PARSER = new com.google.protobuf.AbstractParser<NetVehicleState>() {
      public NetVehicleState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NetVehicleState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetVehicleState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetVehicleState> getParserForType() {
      return PARSER;
    }

    public com.blastedstudios.thrall.network.Messages.NetVehicleState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_NetVehicleState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_NetVehicleState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025network/network.proto\022\005proto\"M\n\017NetVeh" +
      "icleState\022\r\n\005pos_x\030\001 \001(\002\022\r\n\005pos_y\030\002 \001(\002\022" +
      "\r\n\005vel_x\030\003 \001(\002\022\r\n\005vel_y\030\005 \001(\002B-\n!com.bla" +
      "stedstudios.thrall.networkB\010Messagesb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_NetVehicleState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_NetVehicleState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_NetVehicleState_descriptor,
        new java.lang.String[] { "PosX", "PosY", "VelX", "VelY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
